moved node to https

diff --git a/Frontend/Dockerfile b/Frontend/Dockerfile
--- a/Frontend/Dockerfile
+++ b/Frontend/Dockerfile
@@ -3,14 +3,24 @@ FROM node:23-alpine-slim@sha256:86703151a18fcd06258e013073508c4afea8e19cd7ed4515
 WORKDIR /app
 
 COPY package.json ./
-
-RUN npm install
-
-
 COPY . .
 
-ENV NODE_EXTRA_CA_CERTS=/etc/nginx/ssl/transcendence.pem
 
+RUN npm install
+RUN apk add --no-cache openssl
+RUN mkdir -p certs
+
+
+
+
+RUN openssl req -x509 -nodes -newkey rsa:2048 -out certs/server.crt -keyout certs/server.key \
+-subj "/C=FR/ST=Seine-et-Marne/L=Vernou/O=Ecole\ 42/OU=Ecole/CN=transcendence.fr/emailAddress=ehouot@student.42nice.fr"
+
+# Combine the two certificates (internal + external)
+RUN cat /app/certs/server.crt > /etc/ssl/certs/combined.pem
+
+# Tell Node to trust the combined certs
+ENV NODE_EXTRA_CA_CERTS=/etc/ssl/certs/combined.pem
 ARG NEXT_PUBLIC_WS_HOST
 ARG NEXT_PUBLIC_WS_PORT
 ARG NEXT_PUBLIC_API_URL
@@ -21,6 +31,9 @@ ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
 
 
 RUN npm run build
+#RUN ls -la /app /app/dist /app/certs && cat /app/dist/server.js && [ -f /app/dist/baba.js ] || (echo "❌ server.ts NOT FOUND" && exit 1)
+
+#ENTRYPOINT ["/app/entrypoint.sh"]
 
 CMD ["npm", "run", "start"]
 # CMD ["npm", "run", "dev"]
